#!/bin/bash
# original from http://stackoverflow.com/a/2514279

main=`git remote show origin | sed -n '/HEAD branch/s/.*: //p'`

for branch in `git branch -r | grep -v HEAD`
do
    BRANCHLATEST=`git rev-parse $branch`
    ANCESTOR=`git merge-base $main $branch`
    MERGED=''
    if [ "$BRANCHLATEST" = "$ANCESTOR" ] ; then
       MERGED='(MERGED)' 
    fi
    echo -e `git show --format="%ci %cr %ce $MERGED" $branch | head -n 1` \\t$branch;
done 

